### ISSUE TITLE
tried to use server, got 'Error: could not find function "server"'

### ISSUE THREAD

**Issue by kushtun** [schloerke/gqlr#3]
I was walking through the README, and all ran well, ouptuts as depicted, until I tried the server line; 

`server(star_wars_schema, log = TRUE)`

- failed with the error message above (`Error: could not find function "server"`).  

Haven't dug through the code -- is there perhaps another dependency, or...?

**Comment by rossgore** [comment]
Also encountering this issue. Tried install the jug package since that was referred to in other documentation but still no luck.

**Comment by schloerke** [comment]
@kushtun @rossgore 

So sorry about that. I forgot to export the method.  

It should work with `gqlr:::server`.  That's my fault.

I need to remove the `jug` support and have it be a programatic `plumber` call.  I hope to get to this soon.

**Comment by schloerke** [comment]
@rossgore jug should still be available on CRAN.  https://cran.r-project.org/web/packages/jug/index.html

**Comment by schloerke** [comment]
Fixed in latest cran release.  Thank you for your patience!
