### ISSUE TITLE
add graphiql support

### ISSUE THREAD

**Issue by schloerke** [schloerke/gqlr#5]
https://github.com/graphql/graphiql

**Comment by andrewgryan** [comment]
I've taken a look at this by using a CDN version of graphiql. I think the only missing ingredient is to add support for `subscriptionType` to the introspection query and return `null` to indicate subscriptions aren't supported.

<img width="1440" alt="Screenshot 2022-11-29 at 15 52 14" src="https://user-images.githubusercontent.com/22789046/204577657-b76a5a4f-a3c8-45c6-9070-f3518509992e.png">

Is this the part of the code base where a `subscriptionType` resolver needs to be added? https://github.com/schloerke/gqlr/blob/49b513fdae5a5ac48aec40ab8301858b64531be5/R/R6-4-introspection.R#L14

I presume once the introspection query is fixed up, it'll just be a case of serving the CDN version of graphiql.

**Comment by schloerke** [comment]
@andrewgryan I've added support in #11 . It should be merged into `master` shortly. 

GraphiQL so nice now! It was fairly clunky when I first made the package.
