### ISSUE TITLE
RStudio Connect deployment

### ISSUE THREAD

**Issue by jlfsjunior** [schloerke/gqlr#7]
Hi @schloerke,

Thanks for the package, graphQL is a super interesting technology and it's great to have it in R...

I've been playing around with the package in the past days and I was curious to see if there is a "hacky" (or not) way to deploy one example similar to yours in RStudio Connect somehow...? 

Thanks!

**Comment by schloerke** [comment]
Oh! Good idea. Mind trying this out?  

Make a `entrypoint.R` file that `plumber` uses for programatic deployment.  Set the port to `NULL` to avoid running the router.  This should allow for the api to be deployed.

```r
# entrypoint.R

library(gqlr)

# load `star_wars_schema`
# ... not ideal, but it works
eval(parse("https://raw.githubusercontent.com/schloerke/gqlr/master/tests/testthat/star_wars_schema.R"))
# show that it was loaded
star_wars_schema$get_schema()

gqlr::server(star_wars_schema, port = NULL)
```

Then to deploy:
```r
rsconnect::deployAPI("~/path/to/entrypoint/folder/", server = "SERVER")
```

Landing page of plumber app on connect:

![Screen Shot 2020-08-20 at 2 21 09 PM](https://user-images.githubusercontent.com/93231/90810067-67d0ff80-e2f0-11ea-8041-0acedf45b088.png)


(You may need the dev version of `plumber` (`rstudio/plumber`) to not require `plumber.R` to exist.)

**Comment by jlfsjunior** [comment]
Works as expected! Thanks!
